baseURL = '/'
languageCode = 'en-us'
title = "Arun Mathai"
copyright = "Arun Mathai" 
theme = 'typo'

# Lists parameters
[params]
theme = 'auto'
colorPalette = 'gruvebox'
hideHeader = false
paginationSize = 100
listDateFormat = '02 Jan 2006'
toc = false
showFooter = true
footerContent = """
All content licensed under CC BY-SA 4.0 license unless otherwise stated. Copyright Â© 2025 Arun Mathai.
"""

[taxonomies]
tag = 'tags'

[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "Weblog"
url = "/weblog"


[[params.menu]]
name = "Notes"
url = "/notes"

[[params.menu]]
name = "Tags"
url = "/tags"

[[params.menu]]
name = "Contact Me"
url = "/contact-me"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'bw'


[[params.social]]
name = "github"
url = "https://github.com/arunmathaisk"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/arunmathaisk"


[[params.social]]
name = "x"
url = "https://x.com/arunmathaisk"


[[params.social]]
name = "instagram"
url = "https://instagram.com/arunmathaisk"


[params.umami]
enable = true
websiteId = "f727cce7-f2e8-4f29-8c51-a5400fe35123"
jsLocation = "https://cloud.umami.is/script.js"

[params.breadcrumbs]
enabled = true 

# Deploy settings

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false


[permalinks]
  weblog = '/weblog/:slug'
  notes = '/notes/:slug'
